### ISSUE TITLE
WMS

### ISSUE THREAD

**Issue by KoalaGeo** [AuScope/geomodelportal#1]
Hi, 

Added WMS layer as below:
```
        "WMS Layers": [
            {
               "display_name": "GBR BGS 1:625k Bedrock INSPIRE Lithology",
               "displayed": true,
               "include": true,
               "model_url": "http://ogc.bgs.ac.uk:80/digmap625k_gsml_insp_gs/ows",
               "name": "gsmlp:GBR_BGS_625k_BLT_INSP",
               "type": "WMSLayer",
                "version": "1.3.0"
            }
       ],
```

I've checked the request being sent, which is [http://ogc.bgs.ac.uk/digmap625k_gsml_insp_gs/ows?SERVICE=WMS&REQUEST=GetMap&LAYERS=gsmlp:GBR_BGS_625k_BLT_INSP&VERSION=1.3.0&STYLES=&FORMAT=image/png&TRANSPARENT=true&BBOX=-471805.38,7522768.30,-462681.24,7530446.90&CRS=EPSG:3857&WIDTH=256&HEIGHT=256](url) which works in the browser. 

However the application is getting a 504 error (timeout)....

![image](https://user-images.githubusercontent.com/33657876/74926690-35405b80-53ce-11ea-8ec0-1c928cd44afa.png)

Any ideas? Something to do with the proxy?

**Comment by KoalaGeo** [comment]
Firstly, from your Linux shell prompt, install “uwsgi” (https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html)

pip3 install uwsgi


Secondly, in your “geomodelportal” repo, edit “ui/proxy.conf.json”. 
Change: “target": “http://localhost”,  to “target”: “http://localhost:4040”,
Then “npm start”


Thirdly, in your “geomodel-2-3dweb” repo (from another shell prompt on the same machine):

cd scripts
touch dummy.db
./build_api_dir.sh dummy.db
tar xvf 202002*-api.tar
cd api
uwsgi --http :4040 --wsgi-file index.py

**Comment by vjf** [comment]
Solution has been provided and the README.md file has also been updated.
